---
weatherapi:
  url: http://api.openweathermap.org/data/2.5/weather
  keys:
    - fedfc67ec822c2257583b17d01e423a3
    - 71793f5b02bb0fe98c7b8720c76cb9f9
    - d49ebe764fe53c5ca867f87c1ce9c6c7
    - 41b8ce2c3caa7d8804dd27bac339fa42
    - 8eccabe0fad952681a81b7c4f7f2a2d1
server:
  servlet:
    context-path: /weather
spring:
  datasource:
    platform: h2
    url: jdbc:h2:mem:weatherdb
  h2:
    console:
      enabled: true
      path: /h2-console
  cache:
    cache-names:
      - api-key-rate-limit
    caffeine:
      spec: maximumSize=1000000,expireAfterAccess=3600s
bucket4j:
  enabled: true
  filters:
    - cache-name: api-key-rate-limit
      http-response-body: '{ "status": 429, "error": "Limit Reached", "message": "You have exceeded the hourly limit" }'
      url: /weather/data/description
      rate-limits:
        - expression: getHeader('x-api-key')
          execute-condition: getHeader('x-api-key').equals('fedfc67ec822c2257583b17d01e423a3') OR getHeader('x-api-key').equals('71793f5b02bb0fe98c7b8720c76cb9f9') OR getHeader('x-api-key').equals('d49ebe764fe53c5ca867f87c1ce9c6c7') OR getHeader('x-api-key').equals('41b8ce2c3caa7d8804dd27bac339fa42') OR getHeader('x-api-key').equals('8eccabe0fad952681a81b7c4f7f2a2d1')
          bandwidths:
            - capacity: 5
              time: 1
              unit: Hours