openapi: 3.0.3
info:
  title: Api Documentation
  description: Api Documentation
  termsOfService: 'urn:tos'
  contact: {}
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0'
  version: '1.0'
servers:
  - url: 'http://localhost:8080'
    description: Inferred Url
tags:
  - name: weather-controller
    description: Weather Controller
paths:
  /weather/data/description:
    get:
      tags:
        - weather-controller
      summary: Retrieve Weather Description
      description: This endpoint retrieve Weather Description based on Country And City
      operationId: getWeatherDescriptionUsingGET
      parameters:
        - name: county
          in: query
          description: Country Name
          required: true
          style: form
          schema:
            type: string
        - name: city
          in: query
          description: City Name
          required: true
          style: form
          schema:
            type: string
        - name: x-api-key
          in: header
          description: API Key
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Weather Description
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/WeatherResponse'
        '400':
          description: Invalid Request Parameters
        '401':
          description: Invalid API Key
        '403':
          description: Forbidden
        '404':
          description: WeatherData Not Found
        '429':
          description: 'API  Key Rate Limit '
components:
  schemas:
    WeatherResponse:
      title: WeatherResponse
      type: object
      properties:
        description:
          type: string
